Pin importlib-resources
This is an attempt to fix an error when running `pre-commit`:

```
Traceback (most recent call last):
  File "/opt/circleci/.pyenv/versions/3.5.2/bin/pre-commit", line 7, in <module>
    from pre_commit.main import main
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pre_commit/main.py", line 11, in <module>
    from pre_commit import git
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pre_commit/git.py", line 7, in <module>
    from pre_commit.util import cmd_output
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pre_commit/util.py", line 21, in <module>
    from importlib_resources import open_binary
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/importlib_resources/__init__.py", line 31, in <module>
    from importlib_resources._py3 import (
  File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/site-packages/importlib_resources/_py3.py", line 20, in <module>
    Resource = Union[str, os.PathLike]
AttributeError: module 'os' has no attribute 'PathLike'
```

`importlib-resources` 3.3.0 came out yesterday, so I think that's the cause. Hopefully, pinning to the previous version works around it.